import { workspace } from "vscode";

export const FILE_NAME = ".gitignore";

export const MESSAGES = {
    network_error: "There was a problem reaching gitignore.io. Try again.",
    fetching: "Fetching list from gitignore.io...",
    generated: `Your ${FILE_NAME} file has been [action]!`,
    generating: `Generating ${FILE_NAME} file...`,
    save_error: `There was an error while saving ${FILE_NAME} file.`,
};

export const PLACEHOLDERS = {
    location: `Where should ${FILE_NAME} file be generated?`,
    override: `${FILE_NAME} file exists. Do you want to override it?`,
    selection_hint: "Select using Space or by clicking",
};

export function getConfig() {
    const config = workspace.getConfiguration("gitignoreGenerator");
    return {
        API_URL: config.get("primaryApiUrl", "https://www.toptal.com/developers/gitignore/api"),
        ALTERNATIVE_API_URL: config.get("fallbackApiUrl", "https://gitignore.palarz.pl"),
        GITHUB_GITIGNORE_URL: config.get("githubRepository", "https://raw.githubusercontent.com/github/gitignore/refs/heads/main"),
        BANNER: config.get("bannerMessage", "File created using '.gitignore Generator' for Visual Studio Code: https://bit.ly/vscode-gig"),
        CUSTOM_RULES_HEADER: config.get("customRulesHeader", "Custom rules (everything added here won't be overriden by 'Generate .gitignore File' if you use 'Update' option)"),
        AUTO_GENERATED_HEADER: config.get("autoGeneratedHeader", "Auto-generated templates"),
        PREFER_GITHUB: config.get("preferGithub", true),
    };
}

// Default exports for backward compatibility
export const API_URL = "https://www.toptal.com/developers/gitignore/api";
export const ALTERNATIVE_API_URL = "https://gitignore.palarz.pl";
export const GITHUB_GITIGNORE_URL = "https://raw.githubusercontent.com/github/gitignore/refs/heads/main";
export const BANNER = "File created using '.gitignore Generator' for Visual Studio Code: https://bit.ly/vscode-gig";
export const USER_RULES = "Custom rules (everything added below won't be overriden by 'Generate .gitignore File' if you use 'Update' option)";

export const OVERRIDE_OPTIONS = [
    {
        label: "Override",
        description: `Overrides entire ${FILE_NAME} file`,
    },
    {
        label: "Update",
        description: `Updates ${FILE_NAME} file keeping existing and user-defined rules`,
    },
];
