import { workspace } from "vscode";

export const FILE_NAME = ".gitignore";

export enum PreferredSource {
    GitHub = "github",
    PrimaryApi = "primaryApi",
    FallbackApi = "fallbackApi",
}

export const SOURCE_PRIORITY_CHAIN: PreferredSource[] = [
    PreferredSource.GitHub,
    PreferredSource.PrimaryApi,
    PreferredSource.FallbackApi,
];

export const MESSAGES = {
    network_error: "There was a problem reaching the configured sources. Try again.",
    fetching: "Fetching templates...",
    fetching_from: (source: string) => `Fetching from ${source}...`,
    generated: `Your ${FILE_NAME} file has been [action]!`,
    generating: `Generating ${FILE_NAME} file...`,
    save_error: `There was an error while saving ${FILE_NAME} file.`,
    fallback_github_timeout: "GitHub repository timeout (10s). Retrying... Falling back to Primary API.",
    fallback_github_404: "GitHub repository unavailable (404). Using Primary API instead.",
    fallback_primary_ratelimit: "Primary API rate limited (429). Using Fallback API.",
    fallback_github_connection: "GitHub repository unreachable. Falling back to Primary API.",
    all_sources_failed: "Unable to fetch templates from all sources. Please check your connection and try again.",
};

export const PLACEHOLDERS = {
    location: `Where should ${FILE_NAME} file be generated?`,
    subdirectory: "Select or type a subdirectory (or press Escape to cancel)",
    override: `${FILE_NAME} file exists. Do you want to override it?`,
    selection_hint: "Select using Space or by clicking",
};

export function getConfig() {
    const config = workspace.getConfiguration("gitignoreGenerator");

    // Read preferred source, with backward compatibility for old preferGithub setting
    let preferredSource = config.get("preferredSource", "github") as string;
    const oldPreferGithub = config.get("preferGithub");
    if (oldPreferGithub !== undefined && oldPreferGithub !== true) {
        // User had preferGithub=false, migrate to fallbackApi for backward compat
        preferredSource = "fallbackApi";
    }

    return {
        // URLs for different sources
        API_URL: config.get("primaryApiUrl", "https://www.toptal.com/developers/gitignore/api"),
        ALTERNATIVE_API_URL: config.get("fallbackApiUrl", "https://gitignore.palarz.pl"),
        GITHUB_GITIGNORE_URL: config.get("githubRepository", "https://raw.githubusercontent.com/github/gitignore/refs/heads/main"),

        // Display and formatting
        BANNER: config.get("bannerMessage", "File created using '.gitignore Generator' for Visual Studio Code: https://bit.ly/vscode-gig"),
        CUSTOM_RULES_HEADER: config.get("customRulesHeader", "Custom rules (everything added here won't be overriden by 'Generate .gitignore File' if you use 'Update' option)"),
        AUTO_GENERATED_HEADER: config.get("autoGeneratedHeader", "Auto-generated templates"),

        // New: Preferred source preference (enum-based)
        PREFERRED_SOURCE: preferredSource as PreferredSource,

        // New: Auto-select mode for Override/Update decisions
        AUTO_SELECT_MODE: config.get("autoSelectMode", true),

        // New: Failover chain resilience settings
        REQUEST_TIMEOUT: config.get("requestTimeout", 10000),
        MAX_RETRIES: config.get("maxRetries", 3),
        ENABLE_DEBUG_LOGGING: config.get("enableDebugLogging", false),
        SHOW_FALLBACK_NOTIFICATION: config.get("showFallbackNotification", true),

        // New: Generated file customization
        INCLUDE_METADATA: config.get("includeMetadata", true),
        INCLUDE_DOCUMENTATION: config.get("includeDocumentation", true),

        // Legacy: kept for backward compatibility
        PREFER_GITHUB: preferredSource === "github",
    };
}

// Default exports for backward compatibility
export const API_URL = "https://www.toptal.com/developers/gitignore/api";
export const ALTERNATIVE_API_URL = "https://gitignore.palarz.pl";
export const GITHUB_GITIGNORE_URL = "https://raw.githubusercontent.com/github/gitignore/refs/heads/main";
export const BANNER = "File created using '.gitignore Generator' for Visual Studio Code: https://bit.ly/vscode-gig";
export const USER_RULES = "Custom rules (everything added below won't be overriden by 'Generate .gitignore File' if you use 'Update' option)";

export const OVERRIDE_OPTIONS = [
    {
        label: "Override",
        description: `Overrides entire ${FILE_NAME} file`,
    },
    {
        label: "Update",
        description: `Updates ${FILE_NAME} file keeping existing and user-defined rules`,
    },
];
